### ISSUE TITLE
plugindir set wrong on debian based distros

### ISSUE THREAD

**Issue by cz172638** [grahamwhiteuk/Networkmanager-anyconnect#2]
while rhel like distros have /usr/lib64 on debian architecture libdir is /usr/lib/ + gcc triplet /usr/lib/x86_64-linux-gnu,  /usr/lib/aarch64-linux-gnu and so on), so check for machine architecture sets forcibly /usr/lib64 overriding libdir, where are other plugins for networkmanager.

**Comment by grahamwhiteuk** [comment]
Thanks for the report.  Before I dig into this, it's worth asking whether you have a proposed fix/patch?
